#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run syncenv && git add . && lint-staged
npx lint-staged
npm run syncenv && git add . && lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
